"""
Django settings for hotel_app project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os

import dj_database_url
import django_on_heroku

# from dotenv import load_dotenv
from pathlib import Path


# load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('HOTEL_APP_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.environ.get('DEBUG_VALUE') == 'True')

ALLOWED_HOSTS = ['127.0.0.1', 'https://sleepy-shore-31933.herokuapp.com']

AUTH_USER_MODEL = 'authentication.User'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.AllowAllUsersModelBackend',
    'authentication.backends.CaseInsensitiveModelBackend',
    'django.contrib.auth.backends.ModelBackend'
)

# Application definition

INSTALLED_APPS = [
    'django_admin_env_notice',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',

    # Project apps
    'authentication',
    'booking',
    'registration',
    'payment',

    # Third party apps
    'widget_tweaks',
    'phonenumber_field',
    'debug_toolbar',
    'django_extensions',
    'admin_honeypot',
]

PAYSTACK_PUBLIC_KEY = os.getenv("PAYSTACK_PUBLIC_KEY")
PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY")

PHONENUMBER_DEFAULT_REGION = "NG"
PHONENUMBER_DEFAULT_FORMAT = "NATIONAL"

MIDDLEWARE = [
    # Whitenoise Middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Third party apps
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]


INTERNAL_IPS = ['127.0.0.1']

ROOT_URLCONF = 'hotel_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Third party apps
                'django_admin_env_notice.context_processors.from_settings',

                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotel_app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


# Postgres database configuration

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get("HOTEL_DB_NAME"),
        'USER': os.environ.get("HOTEL_DB_USER"),
        'PASSWORD': os.environ.get("HOTEL_DB_PASSWORD"),
        'HOST': 'localhost',
        'PORT': '5432',
    }

}

# postgres://hhhkbqszwuieab:af7eabf04d13e786757d345223d4777c323c97d4765fb3d459608eec800bdc2f@ec2-3-220-76-94.compute-1.amazonaws.com:5432/dcrng4d58o8fc4

db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


STATICFILES_DIRS = [
    (BASE_DIR / 'static'),
    # (BASE_DIR / 'media'),
]

STATIC_URL = '/static/'
# MEDIA_URL = '/media/'

STATIC_ROOT = BASE_DIR / 'staticfiles'
# MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

django_on_heroku.settings(locals())

ENVIRONMENT_NAME = 'Development server'
ENVIRONMENT_COLOR = '#FF2222'

ENVIRONMENT_ADMIN_SELECTOR ='grp-header'

ENVIRONMENT_FLOAT = True

ADMINS = [('McDonald', 'mcdonaldotoyo44@proton.me')]

ADMIN_HONEYPOT_EMAIL_ADMINS = True

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

USE_THOUSAND_SEPARATOR = True

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True

    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    
# Debugging server email 
# python -m smtpd -n -c DebuggingServer localhost:1025

# if DEBUG:
#     EMAIL_HOST = 'localhost'
#     EMAIL_PORT = 1025

EMAIL_PORT = 587
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_FROM_USER = 'mcdonaldotoyo44@gmail.com'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True

PASSWORD_RESET_TIMEOUT = 300

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
DEFAULT_FILE_STORAGE = 'storages.backends.dropbox.DropBoxStorage'

# DROPBOX_ROOT_PATH = '/media/'
DROPBOX_OAUTH2_TOKEN = os.environ.get('DROPBOX_OAUTH2_TOKEN')
# DROPBOX_APP_KEY = os.environ.get('DROPBOX_APP_KEY')
# DROPBOX_APP_SECRET = os.environ.get('DROPBOX_APP_SECRET')
# DROPBOX_OAUTH2_REFRESH_TOKEN = os.environ.get('DROPBOX_OAUTH2_REFRESH_TOKEN')
