# Generated by Django 3.2.8 on 2022-09-17 10:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_rename_phone_hotel_phone_number'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)])),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_code', models.CharField(max_length=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hotel')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
