# Generated by Django 3.2.8 on 2022-09-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_rename_phone_hotel_phone_number'),
        ('payment', '0002_hotelaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelaccount',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.hotel'),
        ),
    ]
