# Generated by Django 3.2.8 on 2022-09-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_rename_phone_hotel_phone_number'),
        ('payment', '0003_alter_hotelaccount_hotel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelAccount',
            new_name='HotelBankAccount',
        ),
    ]
