# Generated by Django 3.2.8 on 2022-09-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_rename_phone_hotel_phone_number'),
        ('payment', '0004_rename_hotelaccount_hotelbankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbankaccount',
            name='bank_name',
            field=models.CharField(choices=[('Access Bank Plc', 'Access Bank'), ('Fidelity Bank Plc', 'Fidelity Bank'), ('First City Monument Bank Limited', 'FCMB'), ('First Bank of Nigeria Limited', 'First Bank'), ('Guaranty Trust Holding Company Plc', 'GTB'), ('Union Bank of Nigeria Plc', 'Union Bank'), ('United Bank for Africa Plc', 'UBA'), ('Zenith Bank Plc', 'Zenith Bank'), ('Citibank Nigeria Limited', 'Citibank'), ('Ecobank Nigeria', 'Ecobank'), ('Heritage Bank Plc', 'Heritage Bank'), ('Keystone Bank Limited', 'Keystone Bank'), ('Polaris Bank Limited', 'Polaris Bank'), ('Stanbic IBTC Bank Plc', 'Stanbic IBTC'), ('Standard Chartered', 'Standard Chartered'), ('Sterling Bank Plc', 'Sterling Bank'), ('Titan Trust Bank Limited', 'Titan Trust Bank'), ('Unity Bank Plc', 'Unity Bank'), ('Wema Bank Plc', 'Wema Bank'), ('Globus Bank Limited', 'Globus Bank'), ('Parallex Bank Limited', 'Parallex Bank'), ('Providus Bank Limited', 'Providus Bank'), ('SunTrust Bank Nigeria Limited', 'SunTrust Bank'), ('Jaiz Bank Plc', 'Jaiz Bank'), ('LOTUS BANK', 'Lotus bank'), ('TAJBank Limited', 'TAJBank'), ('Mutual Trust Microfinance Bank', 'Mutual Trust Microfinance Bank'), ('Rephidim Microfinance Bank', 'Rephidim Microfinance Bank'), ('Shepherd Trust Microfinance Bank', 'Shepherd Trust Microfinance Bank'), ('Empire Trust Microfinance Bank', 'Empire Trust Microfinance Bank'), ('Finca Microfinance Bank Limited', 'Finca Microfinance Bank Limited'), ('Fina Trust Microfinance Bank', 'Fina Trust Microfinance Bank'), ('Accion Microfinance Bank', 'Accion Microfinance Bank'), ('Peace Microfinance Bank', 'Peace Microfinance Bank'), ('Infinity Microfinance Bank', 'Infinity Microfinance Bank'), ('Pearl Microfinance Bank Limited', 'Pearl Microfinance Bank Limited'), ('Covenant Microfinance Bank Ltd', 'Covenant Microfinance Bank Ltd'), ('Advans La Fayette Microfinance Bank', 'Advans La Fayette Microfinance Bank'), ('Sparkle Bank', 'Sparkle Bank'), ('Kuda Bank', 'Kuda Bank'), ('Rubies Bank', 'Rubies Bank'), ('VFD Microfinance Bank', 'VFD Microfinance Bank'), ('Mint Finex MFB', 'Mint Finex MFB'), ('Mkobo MFB', 'Mkobo MFB'), ('Coronation Merchant Bank', 'Coronation Merchant Bank'), ('FBNQuest Merchant Bank', 'FBNQuest Merchant Bank'), ('FSDH Merchant Bank', 'FSDH Merchant Bank'), ('Rand Merchant Bank', 'Rand Merchant Bank'), ('Nova Merchant Bank', 'Nova Merchant Bank')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hotelbankaccount',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='registration.hotel'),
        ),
    ]
