# Generated by Django 3.2.8 on 2022-09-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20220918_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbankaccount',
            name='bank_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='hotelbankaccount',
            name='bank_name',
            field=models.CharField(choices=[('Access Bank Nigeria Plc', 'Access Bank'), ('Diamond Bank Plc', 'Diamond Bank'), ('Ecobank Nigeria', 'Ecobank'), ('Enterprise Bank Plc', 'Enterprise Bank'), ('Fidelity Bank Plc', 'Fidelity Bank'), ('First Bank of Nigeria Plc', 'First Bank'), ('First City Monument Bank', 'FCMB'), ('Guaranty Trust Bank Plc', 'GTB'), ('Heritage Banking Company Ltd', 'Heritage Bank'), ('Jaiz Bank', 'Jaiz Bank'), ('Keystone Bank Ltd', 'Keystone Bank'), ('Mainstreet Bank Plc', 'Mainstreet Bank'), ('Skye Bank Plc', 'Skye Bank'), ('Stanbic IBTC Plc', 'Stanbic IBTC'), ('Sterling Bank Plc', 'Sterling Bank'), ('Union Bank Nigeria Plc', 'Union Bank'), ('United Bank for Africa Plc', 'UBA'), ('Unity Bank Plc', 'Unity Bank'), ('WEMA Bank Plc', 'WEMA Bank'), ('Zenith Bank International', 'Zenith Bank')], max_length=200),
        ),
    ]
