# Generated by Django 3.2.8 on 2022-09-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20220918_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbankaccount',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
