# Generated by Django 3.2.8 on 2022-09-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_hotelbankaccount_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbankaccount',
            name='bank_code',
            field=models.CharField(max_length=300),
        ),
    ]
