# Generated by Django 3.2.8 on 2022-09-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_hotelbankaccount_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbankaccount',
            name='paystack_subaccount_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
