# Generated by Django 3.2.8 on 2022-09-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_hotelbankaccount_paystack_subaccount_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
