# Generated by Django 3.2.8 on 2022-09-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_payment_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='authorization_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
