# Generated by Django 3.2.8 on 2022-10-08 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment_authorization_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbankaccount',
            name='account_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelbankaccount',
            name='account_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='hotelbankaccount',
            name='paystack_subaccount_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
