# Generated by Django 3.2.8 on 2022-07-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
