# Generated by Django 3.2.8 on 2022-07-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20220726_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='date_checked_in',
            new_name='date_to_check_in',
        ),
        migrations.RenameField(
            model_name='roombooking',
            old_name='date_checked_out',
            new_name='date_to_check_out',
        ),
    ]
