# Generated by Django 3.2.8 on 2022-07-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20220726_1737'),
        ('booking', '0006_auto_20220726_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('room_number', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hotel')),
                ('room_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roombooking')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
