# Generated by Django 3.2.8 on 2022-07-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20220727_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='date_booked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='date_to_check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='date_to_check_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
