# Generated by Django 3.2.8 on 2022-08-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20220727_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.roombooking'),
        ),
    ]
