# Generated by Django 3.2.8 on 2022-08-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_roombooking_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='room_number',
            new_name='room_booked',
        ),
    ]
