# Generated by Django 3.2.8 on 2022-08-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_rename_room_number_slug_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(),
        ),
    ]
