# Generated by Django 3.2.8 on 2022-08-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('booking', '0016_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.roombooking'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.guest'),
        ),
    ]
