# Generated by Django 3.2.8 on 2022-08-08 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.roombooking'),
        ),
    ]
