# Generated by Django 3.2.8 on 2022-08-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20220813_1311'),
        ('booking', '0019_auto_20220813_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.roomtype'),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
