# Generated by Django 3.2.8 on 2022-08-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20220814_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='number_of_booked_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
