# Generated by Django 3.2.8 on 2022-08-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_auto_20220816_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
