# Generated by Django 3.2.8 on 2022-08-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_rename_images_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='room_images',
            new_name='image',
        ),
    ]
