# Generated by Django 3.2.8 on 2022-08-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_rename_room_images_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.roombooking'),
        ),
    ]
