# Generated by Django 3.2.8 on 2022-08-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_guest_user'),
        ('booking', '0029_alter_room_room_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.guest'),
        ),
    ]
