# Generated by Django 3.2.8 on 2022-08-25 08:24

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_alter_image_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='room',
        ),
        migrations.AddField(
            model_name='image',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.roomtype'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=booking.models.get_room_type_images_filepath),
        ),
    ]
