# Generated by Django 3.2.8 on 2022-08-25 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_auto_20220825_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.roomtype'),
        ),
    ]
