# Generated by Django 3.2.8 on 2022-09-05 07:04

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_alter_image_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, upload_to=booking.models.get_room_type_images_filepath),
        ),
    ]
