# Generated by Django 3.2.8 on 2022-09-05 08:19

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(max_length=255, null=True, upload_to=booking.models.thumbnail_filepath),
        ),
    ]
