# Generated by Django 3.2.8 on 2022-09-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_image_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='RoomTypeImage',
        ),
    ]
