# Generated by Django 3.2.8 on 2022-07-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='date_of_hotel_profile_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_location',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='no_rooms_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='number_of_booked_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='number_of_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.location'),
        ),
    ]
