# Generated by Django 3.2.8 on 2022-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_hotel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='number_of_booked_rooms',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
