# Generated by Django 3.2.8 on 2022-08-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20220726_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='date_of_hotel_profile_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_location',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='number_of_booked_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='number_of_rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(),
        ),
    ]
