# Generated by Django 3.2.8 on 2022-08-12 09:37

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20220803_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='display_image',
            field=models.ImageField(blank=True, default=registration.models.get_default_hotel_image, max_length=255, null=True, upload_to=registration.models.get_hotel_image_filepath),
        ),
    ]
