# Generated by Django 3.2.8 on 2022-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_hotel_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(default='Description', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='full_description',
            field=models.TextField(default='Full description'),
            preserve_default=False,
        ),
    ]
