# Generated by Django 3.2.8 on 2022-08-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='date_of_hotel_profile_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
