# Generated by Django 3.2.8 on 2022-08-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20220813_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='room_types',
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_variety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_varieties', to='registration.roomtype'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.hotel'),
        ),
    ]
