# Generated by Django 3.2.8 on 2022-08-21 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20220813_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='number_of_rooms',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(5)]),
        ),
    ]
