# Generated by Django 3.2.8 on 2022-08-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_hotel_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='number_of_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
