# Generated by Django 3.2.8 on 2022-08-21 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_alter_hotel_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='number_of_rooms',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(5)]),
        ),
    ]
