# Generated by Django 3.2.8 on 2022-08-31 18:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_alter_hotel_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
