# Generated by Django 3.2.8 on 2022-08-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_hotel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
