# Generated by Django 3.2.8 on 2022-10-08 11:54

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_rename_phone_hotel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='display_image',
            field=models.ImageField(default=registration.models.get_default_hotel_image, max_length=255, upload_to=registration.models.get_hotel_image_filepath),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
