# Generated by Django 3.2.8 on 2022-08-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
