# Generated by Django 3.2.8 on 2022-08-11 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='next_of_kin_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone Number', regex='^\\+?1?\\d{9, 15}$')]),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone Number', regex='^\\+?1?\\d{9, 15}$')]),
        ),
    ]
