# Generated by Django 3.2.8 on 2022-08-11 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220811_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='next_of_kin_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone Number', regex='(^[070]\\d{8}$)|(^[080]\\d{8}$)|(^[081]\\d{8}$)|(^[090]\\d{8}$)|(^[091]\\d{8}$)|(^[\\+]?[234]\\d{10}$)')]),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone Number', regex='(^[070]\\d{8}$)|(^[080]\\d{8}$)|(^[081]\\d{8}$)|(^[090]\\d{8}$)|(^[091]\\d{8}$)|(^[\\+]?[234]\\d{10}$)')]),
        ),
    ]
