# Generated by Django 3.2.8 on 2022-08-31 18:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='next_of_kin_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
