# Generated by Django 3.2.8 on 2022-10-08 14:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20220831_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='next_of_kin_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
