# Generated by Django 3.2.8 on 2022-10-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text="Designates whether this user's email is verified.", verbose_name='email_verified'),
        ),
    ]
